# Generated by Django 2.1.7 on 2020-09-11 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200911_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='joining_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
